apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-ui-app
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: simple-ui-app

  template:
    metadata:
      labels:
        app: simple-ui-app

    spec:
      containers:
      - name: simple-ui-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.service.targetPort }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 30
          periodSeconds: 10