replicaCount: 1

image:
  repository: vishnuprasathp/simple-ui-app
  tag: 4857b
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi